### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [LucyClaxton/f1-3-c2p1-colmar-academy#2]
https://github.com/LucyClaxton/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/index.html#L14-L40

You're missing several opportunities to make your markup more semantic by using tags like `header`, `nav`, `main`, `section` and `footer`. 

See if you can go back and make your markup more semantic. This is much better than relying constantly on `div` tags, and can make your code much easier to read and reason about.

**Comment by LucyClaxton** [comment]
Yes, that is something I do keep forgetting to use, thank you for the tips!
