### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by ghost** [LucyClaxton/f1-3-c2p1-colmar-academy#5]
Great job getting this website to resize gracefully 👍  

You really nailed the breakpoints and media queries and made great use of relative font-sizes and widths as well as flexbox to implement your responsive layout.

**Comment by LucyClaxton** [comment]
I'm glad you think so, I found the mobile site one of the most frustrating but seeing it working and looking as expected makes me feel like I have really achieved something!
