### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [LucyClaxton/f1-3-c2p1-colmar-academy#7]
Satisfactory 👍

You're done a great job writing a fully mobile responsive website and should be excited to show off your new skill!

Just for practice you should see if you can make some nice mobile versions of your previous sites. There's no reason why you shouldn't leave this program without a full portfolio mobile responsive websites!

**Comment by LucyClaxton** [comment]
Thank you so much! I really appreciate the feedback and put it into place in my future projects!
